version: '3.1'
services:
  db_production:
    image: postgres:latest
    restart: always
    enviroment:
      POSTGRES_USER: admin
      POSTGRES_DB: production
      POSTGRES_PASSWORD: 123@qWe
    ports:
      - 5432:5432

  db_homolog:
    image: postgres:latest
    restart: always
    enviroment:
      POSTGRES_USER: admin
      POSTGRES_DB: homolog
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432